name = "BesselFunctions"
uuid = "4d59f32e-7137-4000-967d-44acb2105281"
authors = ["Daniel Cocks <daniel.cocks@gmail.com>"]
version = "0.1.0"

[deps]
AndExport = "4484d908-372d-4f90-b90b-0ec97f005b8c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
